Fix AttributeError: 'DataFrame' object has no attribute 'exit_tag'
the older strategies won't have an exit_tag and so the populate_indicator will throw an error